name = "hex-truncated-series-mathlib"
defaultTargets = ["HexTruncatedSeriesMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexTruncatedSeries"
git = "https://github.com/leanprover/hex-truncated-series.git"
rev = "v0.9.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6b7abb3c7686292736be2955bd3eb9ebf63b456a"

[[lean_lib]]
name = "HexTruncatedSeriesMathlib"
